//go:build linux
// +build linux

package shield

// bpf_stub_linux.go — Compile-time stubs for bpf2go autogenerated types.
//
// The real bpfObjects and loadBpfObjects are generated by running:
//
//	go generate ./internal/shield/...
//
// which invokes bpf2go to compile the BPF C program and produce bpf_bpfeb.go / bpf_bpfel.go.
// These stubs silence IDE/linter errors when the generated files have not been committed yet.
// DELETE THIS FILE once you have run `go generate` and the real generated files are present.

import "github.com/cilium/ebpf"

// bpfObjects holds the autogenerated BPF program + map handles.
// Replaced by the real type from bpf2go after `go generate` is run.
type bpfObjects struct {
	XdpFirewall  *ebpf.Program
	BlockedIps   *ebpf.Map
	EbpfConfig   *ebpf.Map
	DropCount    *ebpf.Map
	SynDropCount *ebpf.Map
}

func (o *bpfObjects) Close() error {
	if o.XdpFirewall != nil {
		o.XdpFirewall.Close()
	}
	for _, m := range []*ebpf.Map{o.BlockedIps, o.EbpfConfig, o.DropCount, o.SynDropCount} {
		if m != nil {
			m.Close()
		}
	}
	return nil
}

// loadBpfObjects loads the compiled BPF objects into the kernel.
// Stub — replaced by bpf2go generated version after `go generate`.
func loadBpfObjects(obj *bpfObjects, _ *ebpf.CollectionOptions) error {
	return nil
}
