//go:build linux
// +build linux

package shield

import (
	"encoding/binary"
	"fmt"
	"log"
	"net"
	"sync/atomic"

	"github.com/cilium/ebpf/link"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang bpf ../../ebpf/xdp_filter.c -- -I../../headers

type ebpfShield struct {
	objs         bpfObjects // Autogenerated struct from bpf2go
	ifaceLink    link.Link
	dropCount    atomic.Int64 // Cache counter locally to avoid spamming kernel read
	synRateLimit uint32
}

// New creates a new instance of the eBPF shield driver for Linux.
func New(synRateLimit int) Shield {
	log.Println("[Shield] Selected Driver: eBPF/XDP (Linux Kernel)")
	limit := uint32(synRateLimit)
	if limit <= 0 {
		limit = 0 // 0 means disabled in eBPF
	}
	return &ebpfShield{
		synRateLimit: limit,
	}
}

func (s *ebpfShield) Start() error {
	// 1. Load compiled eBPF ELF into the kernel
	if err := loadBpfObjects(&s.objs, nil); err != nil {
		return fmt.Errorf("loading objects: %w", err)
	}

	// 2. Configure eBPF parameters
	var configKey uint32 = 0
	if err := s.objs.EbpfConfig.Put(&configKey, &s.synRateLimit); err != nil {
		log.Printf("[eBPF] Warning: Failed to set syn_rate_limit in config map: %v", err)
	} else {
		log.Printf("[eBPF] SYN rate limit set to %d/s in Kernel", s.synRateLimit)
	}

	// 3. Attach XDP program to the network interface (e.g. eth0 or lo)
	// Hardcoded "eth0" for demo, in real life this should come from config
	ifaceName := "eth0"
	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		// Fallback to loopback if eth0 doesn't exist to at least not panic in testing
		log.Printf("[eBPF] Warning: %s not found. Falling back to 'lo'. Config your system interface.", ifaceName)
		iface, err = net.InterfaceByName("lo")
		if err != nil {
			return fmt.Errorf("lookup network iface %q: %s", ifaceName, err)
		}
	}

	lnk, err := link.AttachXDP(link.XDPOptions{
		Program:   s.objs.XdpFirewall,
		Interface: iface.Index,
	})
	if err != nil {
		return fmt.Errorf("could not attach XDP program: %s", err)
	}

	s.ifaceLink = lnk
	log.Printf("[eBPF] XDP program successfully attached to interface %d (%s)", iface.Index, iface.Name)
	return nil
}

func (s *ebpfShield) Stop() error {
	var err1, err2 error
	if s.ifaceLink != nil {
		err1 = s.ifaceLink.Close()
	}
	err2 = s.objs.Close()

	if err1 != nil {
		return err1
	}
	return err2
}

func ip2int(ip net.IP) uint32 {
	if len(ip) == 16 {
		return binary.LittleEndian.Uint32(ip[12:16])
	}
	return binary.LittleEndian.Uint32(ip)
}

func (s *ebpfShield) Block(ip string) error {
	parsedIP := net.ParseIP(ip)
	if parsedIP == nil || parsedIP.To4() == nil {
		return fmt.Errorf("invalid IPv4 address: %s", ip)
	}

	// XDP struct map expects LittleEndian conversion
	ipUint32 := ip2int(parsedIP.To4())
	value := uint32(1)

	// Update into Kernel Map
	if err := s.objs.BlockedIps.Put(&ipUint32, &value); err != nil {
		return fmt.Errorf("failed to insert %s into BPF map: %v", ip, err)
	}

	log.Printf("[eBPF] Blocked IP %s at Kernel L3", ip)
	return nil
}

func (s *ebpfShield) Unblock(ip string) error {
	parsedIP := net.ParseIP(ip)
	if parsedIP == nil || parsedIP.To4() == nil {
		return fmt.Errorf("invalid IPv4 address: %s", ip)
	}

	ipUint32 := ip2int(parsedIP.To4())
	if err := s.objs.BlockedIps.Delete(&ipUint32); err != nil {
		// Ignore if doesn't exist
		log.Printf("[eBPF] Could not unblock IP: %v", err)
	}
	return nil
}

func (s *ebpfShield) IsBlocked(ip string) bool {
	// In pure eBPF, we don't query the map from userspace for every request
	// because packets from this IP never reach the proxy's L7 layer anyway!
	return false
}

// ListBlocked returns IPs tracked at the userspace level.
// eBPF-blocked IPs live in the kernel map and are not enumerable from userspace here;
// only userspace-recorded drops are tracked via dropCount. Return empty to signal that
// the reconciler should rely on Redis as source of truth for eBPF mode.
func (s *ebpfShield) ListBlocked() []string {
	return []string{}
}

func (s *ebpfShield) RecordDrop(ip string) {
	// This function might be called by the userspace layer if eBPF misses (e.g. proxy logic block)
	s.dropCount.Add(1)
}

func (s *ebpfShield) GetDropCount() int64 {
	var key uint32 = 0
	var total uint64

	// 1. Read Blocklist Drops
	var blockValues []uint64 // PERCPU yields an array of counters across all CPUs
	if err := s.objs.DropCount.Lookup(&key, &blockValues); err == nil {
		for _, v := range blockValues {
			total += v
		}
	}

	// 2. Read SYN Flood Drops
	var synValues []uint64
	if err := s.objs.SynDropCount.Lookup(&key, &synValues); err == nil {
		for _, v := range synValues {
			total += v
		}
	}

	return int64(total) + s.dropCount.Load()
}
